include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'widgetbook/**'

linter:
  rules:
    - always_use_package_imports
    - require_trailing_commas