name: flutter_template
description: "A Flutter Template Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

workspace:
  - packages/core
  - packages/design_system
  - packages/feature_post

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  core:
    path: packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

  # Externals
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#4285F4"

  android_12:
    color: "#4285F4"
