name: flutter_template
description: "A Flutter Template Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Externals
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  freezed_annotation: ^3.0.0
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  logging: ^1.3.0
  logger: ^2.3.0
  get_it: ^8.0.3
  share_plus: ^11.0.0
  shared_preferences: ^2.3.5
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

  # Externals
  mocktail_image_network: ^1.2.0
  mocktail: ^1.0.4
  build_runner: ^2.4.14
  freezed: ^3.0.6
  json_serializable: ^6.9.0
  widgetbook_generator: ^3.13.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true