name: feature_post
description: "Post feature package with CRUD operations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  core:
    path: ../core
  design_system:
    path: ../design_system

  # State Management (needed for BLoC)
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Dependency Injection (needed for GetIt)
  get_it: ^8.0.3

  # Required for models
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.14
  freezed: ^3.0.6
  json_serializable: ^6.9.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true